export const GET_COURSE_CATEGORIES = 'GET_COURSE_CATEGORIES';
export const GET_COURSE_LIST = 'GET_COURSE_LIST';
export const GET_COURSE_BY_CAT = 'GET_COURSE_BY_CAT';
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL';
export const GET_COURSE_LIST_BY_SEARCH = 'GET_COURSE_LIST_BY_SEARCH';